UR\Entity\Core\DataSourceEntry:
    properties:
        dataSource:
            - NotNull: ~
            - NotBlank: ~
        valid:
            - NotNull: ~
            - NotBlank: ~
        path:
            - NotNull: ~
            - NotBlank:
                message: "path should not be null or blank"
        receivedVia:
            - NotNull: ~
            - NotBlank:
                message: "receivedVia should not be null or blank"