UR\Entity\Core\AutoOptimizationConfig:
    type: entity
    table: core_auto_optimization_config
    repositoryClass: UR\Repository\Core\AutoOptimizationConfigRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
        transforms:
            type: json_array
            nullable: true
        filters:
            type: json_array
            nullable: true
        metrics:
            type: json_array
            nullable: true
        dimensions:
            type: json_array
            nullable: true
        fieldTypes:
            type: json_array
            nullable: false
        joinBy:
            type: json_array
            nullable: true
        factors:
            type: json_array
            nullable: true
        objective:
            type: string
            nullable: true
        expectedObjective:
            type: string
            nullable: true
        dateRange:
            type: string
            nullable: true
        active:
            type: boolean
            nullable: false
            options:
                default: false
        createdDate:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        identifiers:
            type: json_array
            nullable: true
        positiveFactors:
            type: json_array
            nullable: true
        negativeFactors:
            type: json_array
            nullable: true
        token:
            type: string
            nullable: true
    manyToOne:
        publisher:
            targetEntity: UR\Bundle\UserSystem\PublisherBundle\Entity\User
    oneToMany:
        autoOptimizationConfigDataSets:
            targetEntity: UR\Entity\Core\AutoOptimizationConfigDataSet
            mappedBy: autoOptimizationConfig
            fetch: EXTRA_LAZY
            cascade: ['persist', 'remove', 'detach']
            orphanRemoval: true
        learners:
            targetEntity: UR\Entity\Core\Learner
            mappedBy: autoOptimizationConfig
            fetch: EXTRA_LAZY
            cascade: ['remove', 'detach']
            orphanRemoval: true
