UR\Entity\Core\Learner:
    type: entity
    table: core_learner_model
    repositoryClass: UR\Repository\Core\LearnerRepository
    uniqueConstraints:
        Learner_unique_key:
            columns:
                - identifier
                - auto_optimization_config_id
                - type
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        identifier:
            type: string
            nullable: true
        model:
            type: json_array
            nullable: true
        type:
            type: string
        updatedDate:
            type: datetime
            gedmo:
                timestampable:
                on: create
        forecastFactorValues:
            type: json_array
            nullable: true
        categoricalFieldWeights:
            type: json_array
            nullable: true
    manyToOne:
        autoOptimizationConfig:
            targetEntity: UR\Entity\Core\AutoOptimizationConfig