UR\Entity\Core\ReportViewMultiView:
    type: entity
    table: core_report_view_multiview
    repositoryClass: UR\Repository\Core\ReportViewMultiViewRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    uniqueConstraints:
        compound_primary_key:
            columns:
                - report_view_id
                - sub_view_id
    fields:
        filters:
            type: json_array
            nullable: false
        dimensions:
            type: json_array
            nullable: true
        metrics:
            type: json_array
            nullable: true
    manyToOne:
        reportView:
            targetEntity: UR\Entity\Core\ReportView
        subView:
            targetEntity: UR\Entity\Core\ReportView