Tagcade\Bundle\UserBundle\Entity\User:
    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order:
        - id
        - username
        - email
        - roles
        - enabledModules
        - userRoles # camel case without get i.e getUserRoles becomes userRoles
        - last_login
        - enabled
    virtual_properties:
#        getUserRoles: ~
        getEnabledModules:
            groups: [user.summary, user.detail]

    properties:
        id:
            expose: true
            groups: [user.summary, user.detail]
        username:
            expose: true
            groups: [user.summary, user.detail]
        email:
            expose: true
            groups: [user.summary, user.detail]
        lastLogin:
            expose: true
            groups: [user.summary, user.detail]
        enabled:
            expose: true
            groups: [user.summary, user.detail]
