Tagcade\Entity\Core\AdNetwork:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [adnetwork.detail, adnetwork.summary]
        publisher:
            expose: true
            groups: [adnetwork.detail, adnetwork.summary]
        name:
            expose: true
            groups: [adnetwork.detail, adnetwork.summary]
        url:
            expose: true
            groups: [adnetwork.detail]
