UR\Entity\Core\Alert:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [alert.detail, alert.summary]
        code:
            expose: true
            groups: [alert.detail, alert.summary]
        isRead:
            expose: true
            groups: [alert.detail, alert.summary]
        message:
            expose: true
            groups: [alert.detail, alert.summary]
        createdDate:
            expose: true
            groups: [alert.detail, alert.summary]
        publisher:
            expose: true
            groups: [alert.detail, alert.summary]
