UR\Entity\Core\DataSource:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.importhistory]
        publisher:
            expose: true
            groups: [datasource.detail, datasource.summary]
        name:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.importhistory]
        format:
            expose: true
            groups: [datasource.detail, datasource.summary]
        dataSourceIntegrations:
            expose: true
            groups: [datasource.detail, datasource.summary]
        connectedDataSources:
            expose: true
            groups: [datasource.detail]
        alertSetting:
            expose: true
            groups: [datasource.detail, datasource.summary]
        detectedFields:
            expose: true
            groups: [datasource.detail, datasource.summary]
        apiKey:
            expose: true
            groups: [datasource.apikey]
        dataSourceEntries:
            expose: true
            groups: [datasource.detail]
        enable:
            expose: true
            groups: [datasource.detail, datasource.summary]