UR\Entity\Core\DataSet:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit, dataset.importhistory, dataset.inreportview, dataset.share]
        publisher:
            expose: true
            groups: [dataset.detail, dataset.edit, dataset.summary]
        name:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit, dataset.importhistory, dataset.inreportview, dataset.share]
        dimensions:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit, dataset.inreportview]
        metrics:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit, dataset.inreportview]
        createdDate:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit]
        allowOverwriteExistingData:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit]
        connectedDataSources:
            expose: true
            groups: [dataset.detail, dataset.summary]
        mapBuilderEnabled:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit]
        mapBuilderConfigs:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit]
        autoReload:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.edit]
        lastActivity:
            expose: true
            groups: [dataset.detail, dataset.summary]
        totalRow:
            expose: true
            groups: [dataset.summary]
        numChanges:
            expose: true
            groups: [dataset.summary]
        numConnectedDataSourceChanges:
            expose: true
            groups: [dataset.summary]
