UR\Entity\Core\DataSourceEntry:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [dataSourceEntry.detail]
        dataSource:
            expose: true
            groups: [dataSourceEntry.detail]
        valid:
            expose: true
            groups: [dataSourceEntry.detail]
        path:
            expose: true
            groups: [dataSourceEntry.detail]
        metaData:
            expose: true
            groups: [dataSourceEntry.detail]
        receivedDate:
            expose: true
            groups: [dataSourceEntry.detail]