UR\Entity\Core\DataSource:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit, datasource.importhistory, datasource.dataset]
        publisher:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit, datasource.dataset]
        name:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit, datasource.importhistory, datasource.dataset]
        format:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        dataSourceIntegrations:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        connectedDataSources:
            expose: true
            groups: [datasource.detail]
        alertSetting:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        detectedFields:
            expose: true
            groups: [datasource.dataset]
        apiKey:
            expose: true
            groups: [datasource.apikey]
        dataSourceEntries:
            expose: true
            groups: [datasource.detail]
        enable:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        useIntegration:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        lastActivity:
            expose: true
            groups: [datasource.detail, datasource.summary]