UR\Entity\Core\DataSource:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [datasource.detail, datasource.summary]
        publisher:
            expose: true
            groups: [datasource.detail, datasource.summary]
        name:
            expose: true
            groups: [datasource.detail, datasource.summary]
        format:
            expose: true
            groups: [datasource.detail, datasource.summary]
        dataSourceIntegrations:
            expose: true
            groups: [datasource.detail, datasource.summary]
