UR\Entity\Core\DataSource:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit, datasource.importhistory, datasource.dataset, datasource.viewAlert, datasource.missingdate]
        publisher:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit, datasource.dataset]
        name:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit, datasource.importhistory, datasource.dataset, datasource.viewAlert, datasource.missingdate]
        format:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        dataSourceIntegrations:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        connectedDataSources:
            expose: true
            groups: [datasource.detail]
        alertSetting:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        detectedFields:
            expose: true
            groups: [datasource.dataset]
        apiKey:
            expose: true
            groups: [datasource.apikey]
        dataSourceEntries:
            expose: true
            groups: [datasource.detail, datasource.missingdate]
        enable:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        useIntegration:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        lastActivity:
            expose: true
            groups: [datasource.detail, datasource.summary]
        numOfFiles:
            expose: true
            groups: [datasource.detail, datasource.summary]
        dateRange:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        dateRangeBroken:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.missingdate, datasource.edit]
        missingDate:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.missingdate, datasource.edit]
        dateRangeDetectionEnabled:
            expose: true
            groups: [datasource.detail, datasource.summary, datasource.edit]
        dateFields:
            expose: true
            groups: [datasource.detail, datasource.edit]
        dateFieldsFromMetadata:
            expose: true
            groups: [datasource.detail, datasource.edit]
        dateFormats:
            expose: true
            groups: [datasource.detail, datasource.edit]
        fromMetadata:
            expose: true
            groups: [datasource.detail, datasource.edit]
        pattern:
            expose: true
            groups: [datasource.detail, datasource.edit]
        emailAnchorTexts:
            expose: true
            groups: [datasource.detail, datasource.edit]
        backfillMissingDateRunning:
            expose: true
            groups: [datasource.detail, datasource.edit]