UR\Entity\Core\DataSet:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.importhistory]
        publisher:
            expose: true
            groups: [dataset.detail]
        name:
            expose: true
            groups: [dataset.detail, dataset.summary, dataset.importhistory]
        dimensions:
            expose: true
            groups: [dataset.detail, dataset.summary]
        metrics:
            expose: true
            groups: [dataset.detail, dataset.summary]
        createdDate:
            expose: true
            groups: [dataset.detail, dataset.summary]
        connectedDataSources:
            expose: true
            groups: [dataset.detail, dataset.summary]