report_api:
    resource: "@ReportApiBundle/Resources/config/routing.yml"
    prefix:   api/v1

ur_admin_api:
    resource: "@URAdminApiBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/admin/v1

ur_publisher_api:
    resource: "@URUserSystemPublisherBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/publisher/v1

ur_api:
    resource: "@URApiBundle/Resources/config/routing.yml"
    type:   rest
    prefix: /api/v1

ur_public:
    resource: "@URPublicBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/public/v1
