api_get_token:
    path:      /getToken
    defaults:  { _controller: TagcadeApiBundle:Token:getToken }
    methods:  [POST]

api_check_token:
    path:      /checkToken
    defaults:  { _controller: TagcadeApiBundle:Token:checkToken }
    methods:  [POST]

api_ad_network:
    type: rest
    resource: Tagcade\Bundle\ApiBundle\Controller\AdNetworkController
    name_prefix:  api_1_

api_data_source:
    type: rest
    resource: Tagcade\Bundle\ApiBundle\Controller\DataSourceController
    name_prefix:  api_1_
