imports:
    - { resource: services/listeners.yml }
    - { resource: services/service.adnetwork.yml }
    - { resource: services/service.data-source-entry.yml }
    - { resource: services/service.datasource.yml }


parameters:
    # jwt
    tagcade_api.service.jwt_response_transformer.class: Tagcade\Bundle\ApiBundle\Service\JWTResponseTransformer
    tagcade.event.authentication_success_listener.class: Tagcade\Bundle\ApiBundle\EventListener\AuthenticationSuccessListener
    tagcade.event.jwt_created_listener.class: Tagcade\Bundle\ApiBundle\EventListener\JWTCreatedListener

services:
    # handlers
    tagcade.handler.role_handler_abstract:
        class: Tagcade\Handler\RoleHandlerAbstract
        abstract: true
        public: false
        parent : tagcade.handler.handler_abstract
        arguments:
            - @form.factory

    # authentication
    tagcade_api.service.jwt_response_transformer:
        class: %tagcade_api.service.jwt_response_transformer.class%

    tagcade.event.authentication_success_listener:
        class: %tagcade.event.authentication_success_listener.class%
        arguments: [@tagcade_api.service.jwt_response_transformer, @fos_user.user_manager]
        tags:
            -
               name: kernel.event_listener
               event: 'lexik_jwt_authentication.on_authentication_success'
               method: 'onAuthenticationSuccess'
               priority: 10

    tagcade.event.jwt_created_listener:
        class: %tagcade.event.jwt_created_listener.class%
        tags:
            -
                name: kernel.event_listener
                event: 'lexik_jwt_authentication.on_jwt_created'
                method: 'onJWTCreated'

    tagcade_api.mailer.mailer:
        class: Tagcade\Bundle\ApiBundle\Mailer\Mailer
        arguments:
            - '@mailer'
            - '@router'
            - '@templating'
            -
                resetting.template: TagcadeApiBundle:Resetting:email.txt.twig
                from_email:
                    resetting: %tagcade_user_system_publisher.resetting.email.from_email%
                password_resetting_link: %password_resetting_link%
